/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import classes.Jogo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.JogoDAO;

public class ListagemJogos extends javax.swing.JFrame {

    /**
     * Creates new form Portfolio
     */
    public ListagemJogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluirJogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaJogos = new javax.swing.JTable();
        btnAlterarJogo = new javax.swing.JButton();
        btnCadastrarJogo = new javax.swing.JButton();
        txtBuscaJogo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnExcluirJogo.setText("Excluir");
        btnExcluirJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirJogoActionPerformed(evt);
            }
        });

        tblListaJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade", "Plataforma", "Gênero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaJogos);

        btnAlterarJogo.setText("Alterar");
        btnAlterarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarJogoActionPerformed(evt);
            }
        });

        btnCadastrarJogo.setText("Cadastrar");
        btnCadastrarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarJogoActionPerformed(evt);
            }
        });

        txtBuscaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaJogoActionPerformed(evt);
            }
        });
        txtBuscaJogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaJogoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscaJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirJogo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirJogo)
                    .addComponent(btnAlterarJogo)
                    .addComponent(btnCadastrarJogo)
                    .addComponent(txtBuscaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarJogoActionPerformed
        this.dispose();
        new CadJogo().setVisible(true);
    }//GEN-LAST:event_btnCadastrarJogoActionPerformed

    
    private void carregarListaJogos(String filtro) {
        try {
            ArrayList<Jogo> jogos = new JogoDAO().recuperar();
            DefaultTableModel model = (DefaultTableModel) tblListaJogos.getModel();
            //Limpa a tabela 
            model.setNumRows(0);
            for (Jogo jbl : jogos) {
                if (filtro == null || getJogoFiltro(filtro, jbl)) {
                    String[] saida = new String[6];
                    saida[0] = jbl.getCodJogo();
                    saida[1] = jbl.getNomeJogo();
                    saida[2] = jbl.getValorJogo();
                    saida[3] = jbl.getQuantidade();
                    saida[4] = jbl.getPlataformaJogo();
                    saida[5] = jbl.getGeneroJogo();
                    //Incluir nova linha na Tabela
                    model.addRow(saida);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    private boolean getJogoFiltro(String filtro, Jogo jogo) {
        filtro = filtro.toUpperCase();
        if (jogo.getCodJogo().toUpperCase().contains(filtro)) 
            return true;
        
        if (jogo.getNomeJogo().contains(filtro)) 
            return true;
        
        if (jogo.getValorJogo().contains(filtro)) 
            return true;
                
        if (jogo.getQuantidade().contains(filtro)) 
            return true;
        
        if (jogo.getPlataformaJogo().contains(filtro)) 
            return true;
        
        if (jogo.getGeneroJogo().contains(filtro)) 
            return true;
           return false;
    
    }


    private void btnAlterarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarJogoActionPerformed
        try {
            String codJogo = (String) tblListaJogos.getModel().getValueAt(tblListaJogos.getSelectedRow(), 0);
            ArrayList<Jogo> jogos = new JogoDAO().recuperar();
            System.out.println(jogos);
            for (Jogo jogo : jogos) {
                
                if (codJogo.equalsIgnoreCase(jogo.getCodJogo())) {
                    this.dispose();
                    new CadJogo(jogo).setVisible(true);
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_btnAlterarJogoActionPerformed

    private void btnExcluirJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirJogoActionPerformed
        try {
            int respostaJogo = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir", "Exclusão de Jogo", JOptionPane.YES_NO_OPTION);
            if (respostaJogo == JOptionPane.OK_OPTION) {
                String codJogo = (String) tblListaJogos.getModel().getValueAt(tblListaJogos.getSelectedRow(), 0);
                new JogoDAO().excluir(codJogo);
                carregarListaJogos(txtBuscaJogo.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirJogoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregarListaJogos(txtBuscaJogo.getText());
    }//GEN-LAST:event_formWindowOpened

    private void txtBuscaJogoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaJogoKeyReleased
        carregarListaJogos(txtBuscaJogo.getText());
    }//GEN-LAST:event_txtBuscaJogoKeyReleased

    private void txtBuscaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaJogoActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemJogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemJogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarJogo;
    private javax.swing.JButton btnCadastrarJogo;
    private javax.swing.JButton btnExcluirJogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaJogos;
    private javax.swing.JTextField txtBuscaJogo;
    // End of variables declaration//GEN-END:variables

}
